### ISSUE TITLE
Incubating Program: Migrate Discourse's database from PostgreSQL to TiDB

### ISSUE THREAD

**Issue by sykp241095** [pingcap/community#106]
## Incubating Program

Migrate Discourse's database from PostgreSQL to TiDB

#### Summary

Migrate Discourse's database from PostgreSQL to MySQL first, then migrate from MySQL to TiDB.

#### Motivation

As https://asktug.com is running on [Discourse](https://github.com/discourse/discourse), and Discourse is running on PostgreSQL, we want to migrate from Discourse from PostgreSQL to TiDB, for:

1. A big benefit to TiDB Community;
2. Potential interaction with Discourse Community and Ruby On Rails Community;
3. Eat our own dog food; 

#### Estimated Time

30 days

### Your RFC/Proposal?

https://github.com/pingcap/community/pull/109

**Comment by winkyao** [comment]
@sykp241095 Could you please write an RFC or Proposal for your project.

**Comment by winkyao** [comment]
LGTM

**Comment by qiuyesuifeng** [comment]
LGTM
