### ISSUE TITLE
Incubating Program: Add Apache Pulsar to tidb-binlog

### ISSUE THREAD

**Issue by wolfstudy** [pingcap/community#117]
## Incubating Program

Add Apache Pulsar to `tidb-binlog`.

### Summary

`tidb-binlog` is a very nice and efficient Change Data Capture(CDC) tool, introducing a new component [**Apache Pulsar**](https://github.com/apache/pulsar) to further improve the processing power of `tidb-binlog`.

### Motivation

During the Change Data Capture(CDC), we need to ensure the order of the messages. Aka, we need to ensure that DDL arrives before DML. Currently, we use Kafka to process the order of messages, but as you know, Kafka can only guarantee the order of messages within a single partition. If we need to expand the downstream data processing capabilities, sometimes we want more partitions to provide more processing power, but how do we ensure the order of messages at this time? This is a trickier question.

Here, please allow me to introduce a new feature of Apache Pulsar: [key_shared](https://pulsar.apache.org/docs/en/concepts-messaging/#key_shared) It ensures that messages are distributed to the key in order different partitions, this sounds like a very nice feature. Can help `tidb-binlog`  to improve processing performance, at the same time, Pulsar has other great features, please refer to [Apache Pulsar](https://pulsar.apache.org/en/).

This is one of the reasons I introduce Apache Pulsar, and the other is we can consider making `tidb-binlog` support pluggable interfaces while allowing support for Kafka, Pulsar and other message queues, which can give users more choices.

### Estimated Time

30 days

**Comment by siddontang** [comment]
PTAL @GregoryIan

**Comment by winkyao** [comment]
@wolfstudy Thanks for your request. Could you please write an RFC or Proposal to https://github.com/pingcap/community/tree/master/rfc, and add a link in the description of this issue?

**Comment by wolfstudy** [comment]
@winkyao PTAL #136 , thanks.

**Comment by GregoryIan** [comment]
I will take a look

**Comment by wolfstudy** [comment]
Thanks @GregoryIan help, @winkyao  #136 has been merged, any update about the issue? Or how we plan for the next step.

**Comment by wolfstudy** [comment]
@winkyao @GregoryIan @siddontang  any update for this?

**Comment by wolfstudy** [comment]
ping @winkyao @GregoryIan @siddontang PTAL thanks.

**Comment by wolfstudy** [comment]
ping @winkyao @GregoryIan @siddontang any update for this?

**Comment by winkyao** [comment]
LGTM

**Comment by wolfstudy** [comment]
@GregoryIan @siddontang PTAL again, thanks

**Comment by IANTHEREAL** [comment]
I suggest integrating Apache Pulsar into ticdc, are there any issues for it? @wolfstudy

**Comment by tisonkun** [comment]
Closed as integrated Apache Pulsar into TiCDC by https://github.com/pingcap/ticdc/pull/751
