### ISSUE TITLE
Incubating Program: fuzz and auto debug

### ISSUE THREAD

**Issue by DQinYuan** [pingcap/community#124]
## Incubating Program

General fuzz and auto debug tool.

### Summary

A tool supports SQLFuzz and General Fuzz by mutation, then detects suspicious code block leading to bugs in fuzz automatically by monitoring code execution path of application. 

### Motivation

There is a lot of uncertainty in Chaos and fuzz test of complicated software like tidb.
Developers often costs a few of weeks to localize the root cause.
this tool may help on this.

### Estimated Time
90 days

### Your RFC/Proposal?
https://github.com/pingcap/community/pull/125

**Comment by tisonkun** [comment]
Closed as RFC merged.
