### ISSUE TITLE
Incubating Program: Talent Plan Courses

### ISSUE THREAD

**Issue by JinLingChristopher** [pingcap/community#130]
# Incubating Program

Talent Plan Courses

### Summary

The proposal is for Talent Plan Courses, which is a series of courses about computer systems, also TiDB. The purpose of the courses is to help more people enter the field of TiDB or computer infrastructure.

### Motivation

Since there are plenty of people interested in TiDB but lack background knowledge, so we propose to create a series of computer system courses to help those people enter the field of the TiDB ecosystem, also computer system infrastructure. Course participants should have developed good knowledge and skills in system programming after consumed course materials.

### Your RFC/Proposal?
[#140 ](https://github.com/pingcap/community/pull/140)

**Comment by hi-rustin** [comment]
/close

The issue has not been replied for a long time, so I will close the issue.

If the issue needs to be discussed, please reply to request reopen, and I will reopen the issue for you.
