### ISSUE TITLE
Incubating Program: Cherry Bot

### ISSUE THREAD

**Issue by you06** [pingcap/community#165]
## Incubating Program

Cherry Bot

#### Summary

Cherry Bot is a bot which helps you automate some work on github. It provides many features including.

Features:

- Cherry Pick: bot can automatically cherry pick PRs to other branches when PR get merged.
- Auto Merge: for the PRs which have been reviewed and are waiting for CI is completed, bot can merge the PRs when you are away form keyboard.
- Label Contributor: bot can add specified label for contributors which may helps your project management.
- Notice: bot helps you find out unlabled issues, not reviewed and stale PRs.
- Slack: the bot is integrated with Slack, you can get the latest status from Slack.
- More features: some features are not such frequently used, but it will bring surprise when you are required.

#### Motivation

Manually cherry pick spend a lot of time, waiting for CI completed makes people tired. GitHub brings good experience for manually usage, however, we need some automatics. We also want our repositories being managed under some rules, which is benefit for maintainance and statistics. While working with GitHub, we always want some feature that GitHub does not offer, which engaged us to make the bot much more stronger.

#### Estimated Time

2 months

### Your RFC/Proposal?

https://github.com/pingcap/community/pull/164

**Comment by zz-jason** [comment]
LGTM

**Comment by winkyao** [comment]
LGTM

**Comment by hi-rustin** [comment]
/close

The issue has not been replied for a long time, so I will close the issue.

If the issue needs to be discussed, please reply to request reopen, and I will reopen the issue for you.
