### ISSUE TITLE
Incubating Program: odin 

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/community#196]
## Incubating Program

Odin

#### Summary

Odin is a data generator/load tool which helps you fast generator/load data on TiDB cluster. It provides many features including.

Features:

- fast generate TPCC/TPCH data in csv format(sst format will support in future)
- fast load data to TIDB cluster(by wrap a lightning)

#### Motivation

Now. benchmark is hard for many people. they have to generator much data for hours and then benchmark. We want to speed it up. Fast generate and Fast load to TiDB cluster

#### Estimated Time

2 months

**Comment by winkyao** [comment]
lgtm
