### ISSUE TITLE
Incubating Program: discourse theme asktug

### ISSUE THREAD

**Issue by g1eny0ung** [pingcap/community#203]
## Project Incubating Request

discourse-theme-asktug

#### Summary

discourse-theme-asktug is a custom theme which used in AskTUG.

#### Motivation

Custom discourse, it is difficult to say whether it is a simple or not simple thing. You can overwrite the page by using vanilla javascript and CSS. This is simple. But this is not customizable and destroys the structure of the page.

If not, you need to dive into the discourse source code. You will need to learn such things:

- [handlebars](https://handlebarsjs.com/)
- [emberjs](https://emberjs.com/)
- [sass](https://sass-lang.com/)

This is not simple but It embeds code seamlessly.

And asktug theme uses the second way, make all overwrites can be highly componentized.

Now, this theme is just getting started, it will add more features in the future.

#### Estimated Time

1 month.

### Your RFC/Proposal?

#202

**Comment by winkyao** [comment]
LGTM

**Comment by g1eny0ung** [comment]
@winkyao Thx, Can we merge #202 now?

**Comment by sykp241095** [comment]
LGTM
