### ISSUE TITLE
Incubating Program: tiup-dm

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/community#207]
## Project Incubating Request

tiup-dm

#### Summary

Currently, DM is deployed through ansible, which is less easy to use than TiUP. The deployment of components using TiUP-related ecology is simpler and is a trend after version 4.0. tiup-dm allows DM to be deployed through TiUP components.

#### Motivation
* Launch of incubation project on tiup-dm.
* Make it able to be deployed by tiup.

#### Estimated Time
30 days

### Your RFC/Proposal?

https://github.com/pingcap/community/pull/206

**Comment by tisonkun** [comment]
closed as mentioned at https://github.com/pingcap/community/pull/206#issuecomment-657383647
