### ISSUE TITLE
Incubating Program: TiUP graduates from pingcap-incubator

### ISSUE THREAD

**Issue by lonng** [pingcap/community#240]
### Describe the project you want to incubate:

The project `https://github.com/pingcap-incubator/tiup` has developed almost three monthes and generally available from 2020-05-28. 

This PR proposes that transfer the TiUP from `pingcap-incubator` to `pingcap`.

**Comment by winkyao** [comment]
LGTM

**Comment by siddontang** [comment]
PTAL @queenypingcap 

LGTM

**Comment by winkyao** [comment]
https://github.com/pingcap/tiup. TiUP is transferred to pingcap org, congratulations!
