### ISSUE TITLE
Incubating Project: BigData connectors for TiDB

### ISSUE THREAD

**Issue by sunxiaoguang** [pingcap/community#242]
### Describe the project you want to incubate:
Implement a fully featured and performant TiDB connector support to PrestoDB, PrestoSQL, Flink and miscellanies other BigData systems on top of TiSpark project.

**Comment by winkyao** [comment]
LGTM

**Comment by winkyao** [comment]
what's the name of the project do you want?

**Comment by sunxiaoguang** [comment]
> what's the name of the project do you want?

How about tidb-connectors? We want to implement Flink connector as well.

**Comment by sunxiaoguang** [comment]
> what's the name of the project do you want?

Let's call it TiBigData!!!
It looks a lot better to me😄

**Comment by qiuyesuifeng** [comment]
LGTM

**Comment by winkyao** [comment]
I create a repo: https://github.com/pingcap-incubator/TiBigData

**Comment by tisonkun** [comment]
closed as done.
