### ISSUE TITLE
Rename pingcap-incubator to tidb-incubator

### ISSUE THREAD

**Issue by AndreMouche** [pingcap/community#326]
The mission of PingCAP Incubator is to make the TiDB ecosystem and community more active, let the TiDB community get more contributions from developers and users. Therefore, we believe that the "PingCAP Incubator" cannot express its mission.  So we are going to rename it to "TiDB Incubator"

**Comment by AndreMouche** [comment]
@pingcap/tidb-maintainer PTAL

**Comment by winkyao** [comment]
LGTM

**Comment by jackysp** [comment]
LGTM

**Comment by bb7133** [comment]
LGTM

**Comment by sunxiaoguang** [comment]
LGTM

**Comment by kylin2017** [comment]
LGTM

**Comment by breeswish** [comment]
How about current projects like minitrace-rust which is for TiKV community but in incubating stage? It is a PingCAP project, but is not incubating for TiDB, but incubating for TiKV.

**Comment by winkyao** [comment]
@breeswish I think whatever the minitrace-rust project in pingcap, tidb-incubator or tikv repo. It all makes sense.

**Comment by siddontang** [comment]
LGTM

**Comment by zz-jason** [comment]
LGTM
