### ISSUE TITLE
Graduated Program: TiDB Dashboard

### ISSUE THREAD

**Issue by breeswish** [pingcap/community#332]
[TiDB Dashboard](https://docs.pingcap.com/zh/tidb/stable/dashboard-intro) is GA since TiDB v4.0.0, so that this project can be graduated.

This issue propose to move [its reopsitory](https://github.com/pingcap-incubator/tidb-dashboard) into the [pingcap](https://github.com/pingcap) org.

**Comment by sykp241095** [comment]
@pingcap/community-reviewers Please help review.

**Comment by winkyao** [comment]
@gingerkidney Could you please do a due diligence? follow by the https://github.com/pingcap/community/blob/master/incubator/projects-approval-criteria.md. To make sure that TiDB-Dashboard meets graduation criteria.

**Comment by sykp241095** [comment]
Repo has been transferred to http://github.com/pingcap/tidb-dashboard.
