### ISSUE TITLE
Incubating Project: TIS - Solr based enterprise level, one-stop search center products 

### ISSUE THREAD

**Issue by baisui1981** [pingcap/community#347]
## Project Incubating Request

TIS - Solr based enterprise level, one-stop search center products with high performance, high reliability and high scalability

#### Summary

Use TIS to quickly build enterprise search service for you. TIS includes three components: 
- offline index building platform  
  The data is exported from TiKV through full table scanning, and then the wide table is constructed by local Mr tool, or the wide table is constructed directly by tispark
- incremental real-time channel
 It is transmitted to Kafka downstream through drainer, and real-time stream calculation is carried out by Flink and submitted to search engine to ensure that the data in search engine and tidb are consistent in near real time
- search engine
  currently，based on Solr8

TIS can integrate this component seamlessly and bring users one-stop, out of the box search products

#### Motivation

This proposal mainly realize features  in Execution process of search  products based on TiDB：
- Define the data source process and select the data source table of TiKV
- Building wide table rules based on the selected data table define by pre step
- In the previous step, the index schema is defined by defining the wide table structure, and the machine node is selected to build the index instance
- The binlog message of TiDB is obtained based on drainer, and the channel synchronization of incremental flow calculation based on Flink 
- Script writing of platform automation installation based on ansible

#### Estimated Time

90 days

#### Attach file
[TIS-TiDB.pdf](https://github.com/pingcap/community/files/5537424/TIS-TiDB.pdf)

**Comment by CalvinKirs** [comment]
sounds good to me

**Comment by winkyao** [comment]
Why the binlog message of TiDB is not obtained based on TiCDC?

**Comment by baisui1981** [comment]
> TiCDC



> Why the binlog message of TiDB is not obtained based on TiCDC?

Of course, all the changeable points of the TIS platform have been abstracted to form an extendable extend point, whether drainer or TiCDC is possible.
