### ISSUE TITLE
CONTRIBUTING.md is out of date

### ISSUE THREAD

**Issue by morgo** [pingcap/community#35]
The `contributing.md` file here mentions Go 1.9 and links to Go 1.8 as well.  The current requirement is Go 1.12 though.  It also has out of date advice about dependency management.

I think it makes sense to change the `contributing.md` in pingcap/tidb to be very short with just a link to this location, so there is only one copy that needs to be maintained.

This should help keep it more up-to-date in future.

**Comment by zz-jason** [comment]
in the latest `contributing.md` file we have updated the requirement on `go` to 1.13, which is what we used in the current build system. I think this issue is stale.
