### ISSUE TITLE
REQUEST: New membership for @dragonly

### ISSUE THREAD

**Issue by dragonly** [pingcap/community#406]
### GitHub Username
@dragonly

### SIG you are requesting membership in
Docs SIG committer

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @ran-huang 
- @DanielZhangQD 

### List of contributions to the SIG’s project
- PRs reviewed / authored
  https://github.com/pingcap/docs-tidb-operator/pulls?q=author%3Adragonly+is%3Apr
  21 PRs in total
- Issues responded to
- SIG projects I am involved with

**Comment by hi-rustin** [comment]
@dragonly  After @ran-huang  and @DanielZhangQD  agree to sponsor you and comment in the issue, I will submit a PR to update the membership.

**Comment by ran-huang** [comment]
LGTM

**Comment by hi-rustin** [comment]
> LGTM

Maybe it's better to use +1 to indicate agreement to sponsorship, but LGTM is fine with that.

**Comment by DanielZhangQD** [comment]
+1
