### ISSUE TITLE
Incubating Feature: steam bulk insert in IoT scenario

### ISSUE THREAD

**Issue by fanweixiao** [pingcap/community#408]
## Feature Incubating Request

In the IoT industry, integrated with YoMo to reduce the pressure and the cost when storing data to the cloud.

### Describe the feature you want to incubate:

We are introducing [YoMo](https://yomo.run)  a streaming serverless framework to the IoT industry. In this scenario, IoT devices/sensors always generate data at high frequency, when hundreds of these data sources connected, the writing pressure makes our customers put Kafka before DB, as we know, Cloud Kafka is expensive, result in bad ROI for our customers. By YoMo, developers can implement a bulk insert to the backend database whenever every 10,000 data arrived or every 30s like [yomo-sink-faunadb-example](https://github.com/yomorun/yomo-sink-faunadb-example)

BTW, YoMo was built atop [IETF QUIC Protocol](https://quicwg.org/), and designed as an `event-first` system, as [gRPC is busy implementing over HTTP/3](https://github.com/grpc/grpc/issues/19126), and [here](https://medium.com/safetycultureengineering/grpc-over-http-3-53f41fc0761e), someday these two products can communicate over QUIC, cause in IoT, QUIC shows lots of advantages.

**Comment by c4pt0r** [comment]
Thank you! And really appreciate you also post a FaunaDB example.

**Comment by fanweixiao** [comment]
@c4pt0r We implement one at https://github.com/yomorun/yomo-sink-tidb-example, please check
