### ISSUE TITLE
REQUEST: New membership for handlerww

### ISSUE THREAD

**Issue by handlerww** [pingcap/community#412]
### GitHub Username
@handlerww

### SIG you are requesting membership in
- sig-name: sig-k8s
- role: committer

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @DanielZhangQD 
- @lonng 

### List of contributions to the SIG’s project
- PRs reviewed 40/ authored 24 https://github.com/pingcap/tidb-operator/pulls?q=type%3Apr+reviewed-by%3Ahandlerww
- Issues responded to
- SIG projects I am involved with

**Comment by DanielZhangQD** [comment]
+1

**Comment by hi-rustin** [comment]
>     * PRs reviewed 40/ authored 24

Better put a github search URL.

**Comment by handlerww** [comment]
> > ```
> > * PRs reviewed 40/ authored 24
> > ```
> 
> Better put a github search URL.

done

**Comment by lonng** [comment]
+1
