### ISSUE TITLE
REQUEST: New membership for dragonly

### ISSUE THREAD

**Issue by dragonly** [pingcap/community#414]
### GitHub Username
@dragonly

### SIG you are requesting membership in
- sig-name: sig-k8s
- role: committer

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @DanielZhangQD 
- @lonng 

### List of contributions to the SIG’s project
- PRs [43 reviewed](https://github.com/pingcap/tidb-operator/pulls?q=is%3Apr+reviewed-by%3Adragonly) / [47 authored](https://github.com/pingcap/tidb-operator/pulls?q=is%3Apr+author%3Adragonly)
- [16 Issues responded to](https://github.com/pingcap/tidb-operator/issues?q=is%3Aissue+commenter%3Adragonly+)
- SIG projects I am involved with: tidb-operator

**Comment by lonng** [comment]
+1

**Comment by DanielZhangQD** [comment]
+1
