### ISSUE TITLE
REQUEST: New membership for @handlerww

### ISSUE THREAD

**Issue by handlerww** [pingcap/community#416]
### GitHub Username
handlerww

### SIG you are requesting membership in
- sig-name: sig-docs
- role: reviewer

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @ran-huang
- @DanielZhangQD

### List of contributions to the SIG’s project
- PRs reviewed 8/ authored 5
  https://github.com/pingcap/docs-tidb-operator/pulls?q=author%3Ahandlerww+is%3Apr
  https://github.com/pingcap/docs-tidb-operator/pulls?q=type%3Apr+reviewed-by%3Ahandlerww
- Issues responded to
- SIG projects I am involved with

**Comment by DanielZhangQD** [comment]
+1

**Comment by zhangyangyu** [comment]
Close as stale.
