### ISSUE TITLE
REQUEST: New membership for @wshwsh12

### ISSUE THREAD

**Issue by wshwsh12** [pingcap/community#419]
### GitHub Username
@wshwsh12

### SIG you are requesting membership in
- sig-name: sig-coprocessor
- role: reviwer

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @breeswish 
- @sticnarf

### List of contributions to the SIG’s project
- PRs [11 authored](https://github.com/tikv/tikv/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Awshwsh12+is%3Aclosed)
- SIG projects I am involved with: tikv

**Comment by breeswish** [comment]
LGTM

**Comment by breeswish** [comment]
+1

**Comment by sticnarf** [comment]
+1
