### ISSUE TITLE
REQUEST: New membership for @Yisaer

### ISSUE THREAD

**Issue by Yisaer** [pingcap/community#421]
### GitHub Username
@Yisaer 

### SIG you are requesting membership in
- sig-name: sig-sql-infra
- role: reviewer

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @djshow832 
- @xhebox

### List of contributions to the SIG’s project
- PRs reviewed / authored
- Issues responded to

**Comment by xhebox** [comment]
+1

**Comment by djshow832** [comment]
+1
