### ISSUE TITLE
REQUEST: New membership for @Reminiscent

### ISSUE THREAD

**Issue by Reminiscent** [pingcap/community#423]
### GitHub Username
Reminiscent

### SIG you are requesting membership in
- sig-name: sig-planner
- role: committer

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @qw4990 
- @winoros 

### List of contributions to the SIG’s project
- PRs reviewed / authored
https://github.com/pingcap/tidb/pulls?q=is%3Apr+author%3AReminiscent+is%3Aclosed+label%3Asig%2Fplanner 
https://github.com/pingcap/tidb/pulls?q=is%3Apr+author%3AReminiscent+is%3Aclosed+label%3Acomponent%2Fstatistics
https://github.com/pingcap/tidb/pulls?q=is%3Apr+reviewed-by%3AReminiscent+
- Issues responded to
- SIG projects I am involved with

**Comment by winoros** [comment]
+1

**Comment by qw4990** [comment]
+1
