### ISSUE TITLE
REQUEST: New membership for jyz0309

### ISSUE THREAD

**Issue by jyz0309** [pingcap/community#425]
### GitHub Username
@jyz0309 

### SIG you are requesting membership in
- sig-name: sig-sql-infra
- role: reviewer

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @crazycs520 

### List of contributions to the SIG’s project
- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with

**Comment by crazycs520** [comment]
+1

**Comment by breeswish** [comment]
+1

**Comment by crazycs520** [comment]
cc @hi-rustin

**Comment by breeswish** [comment]
I'm not a sponsor. Remove me from the list XXXXD

**Comment by bb7133** [comment]
> I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

Just curious...what does this mean? @hi-rustin

**Comment by hi-rustin** [comment]
> > I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
> 
> Just curious...what does this mean? @hi-rustin

See the guidelines.

**Comment by hi-rustin** [comment]
> * PRs reviewed / authored
> 
> * Issues responded to
> 
> * SIG projects I am involved with

Please fill these fields.

**Comment by hi-rustin** [comment]
Also, reviewer in sig-sql-infra needs two valid sponsors.

**Comment by djshow832** [comment]
I'm so sorry to tell you that you have only 4 commits with the `sig/sql-infra` label, but the rule is you must have at least 20 commits to be a reviewer.
Don't worry, I believe you can do it!

**Comment by tisonkun** [comment]
closed as unqualified. @jyz0309  you can always reopen this issue or create a new one once you want to request again when qualified.
