### ISSUE TITLE
REQUEST: New membership for zimulala

### ISSUE THREAD

**Issue by zimulala** [pingcap/community#427]
### GitHub Username
@zimulala 

### SIG you are requesting membership in
- sig-name: sig-exec
- role: committer

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @XuHuaiyu 
- @wshwsh12 

### List of contributions to the SIG’s project
- PRs [300+ authored](https://github.com/pingcap/tidb/pulls?page=14&q=is%3Apr+reviewed-by%3Azimulala+%22executor%3A+%22)
- SIG projects I am involved with: sig-sql-infra

**Comment by wshwsh12** [comment]
+1
