### ISSUE TITLE
REQUEST: New membership for Tjianke

### ISSUE THREAD

**Issue by Tjianke** [pingcap/community#432]
### GitHub Username
@Tjianke

### SIG you are requesting membership in
- sig-name: sig-execution
- role: reviewer

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @mmyj
- @Yisaer 

### List of contributions to the SIG’s project
- PRs reviewed / authored: https://github.com/pingcap/tidb/pulls?page=2&q=is%3Apr+author%3ATjianke+is%3Amerged
- Issues responded to:https://github.com/pingcap/tidb/issues?q=assignee%3A%40me
- SIG projects I am involved with: execution/planner

**Comment by mmyj** [comment]
+1

**Comment by Yisaer** [comment]
+1
