### ISSUE TITLE
REQUEST: New membership for csuzhangxc

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/community#435]
### GitHub Username

@csuzhangxc 

### SIG you are requesting membership in
- sig-name: sig-k8s
- role: committer

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @DanielZhangQD 
- @handlerww 

### List of contributions to the SIG’s project
- PRs [reviewed 51](https://github.com/pingcap/tidb-operator/pulls?q=is%3Apr+reviewed-by%3Acsuzhangxc) / [authored 18](https://github.com/pingcap/tidb-operator/pulls?q=is%3Apr+author%3Acsuzhangxc)
- [3 issues responded to](https://github.com/pingcap/tidb-operator/issues?q=is%3Aissue+commenter%3Acsuzhangxc)
- SIG projects I am involved with: tidb-operator

**Comment by handlerww** [comment]
+1

**Comment by DanielZhangQD** [comment]
+1
