### ISSUE TITLE
REQUEST: New membership for @TszKitLo40

### ISSUE THREAD

**Issue by TszKitLo40** [pingcap/community#437]
### GitHub Username
@TszKitlo40

### SIG you are requesting membership in
- sig-name: sig-exec
- role: reviewer

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @XuHuaiyu 
- @wshwsh12 

### List of contributions to the SIG’s project
- PRs [20merged](https://github.com/pingcap/tidb/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3ATszKitLo40+label%3Asig%2Fexecution+is%3Aclosed)
- Issues responded to [issues](https://github.com/pingcap/tidb/issues?q=is%3Aclosed+assignee%3A%40me+)
- sig/exec
- medium issues [20236](https://github.com/pingcap/tidb/issues/20236) [20255](https://github.com/pingcap/tidb/issues/20255)

**Comment by wshwsh12** [comment]
+1
