### ISSUE TITLE
REQUEST: New membership for shhdgit

### ISSUE THREAD

**Issue by shhdgit** [pingcap/community#452]
### GitHub Username
@shhdgit

### SIG you are requesting membership in
- sig-name: sig-diagnosis
- role: committer

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @breeswish 
- @baurine 

### List of contributions to the SIG’s project
- PRs [reviewed 12](https://github.com/pingcap/tidb-dashboard/pulls?q=is%3Apr+reviewed-by%3Ashhdgit+) / [authored 21](https://github.com/pingcap/tidb-dashboard/pulls?q=is%3Apr+author%3Ashhdgit)
- Issues responded to
- SIG projects I am involved with
  - tidb-dashboard

**Comment by breeswish** [comment]
LGTM. Congrats!

**Comment by baurine** [comment]
LGTM, good job!

**Comment by breeswish** [comment]
@hi-rustin PTAL, thanks!
