### ISSUE TITLE
REQUEST: New membership for @JmPotato

### ISSUE THREAD

**Issue by JmPotato** [pingcap/community#456]
### GitHub Username

@JmPotato

### SIG you are requesting membership in

- sig-name: sig-sql-infra
- role: reviewer

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @xhebox 
- @Yisaer 

### List of contributions to the SIG’s project

- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with

**Comment by Yisaer** [comment]
+1

**Comment by xhebox** [comment]
I think the PR reviews are not enough as said in the sig-sql-infra roles-and-organization(20 reviews). I am OK to the promotion but I think we should at least meet this requirement.

Count: https://github.com/pingcap/tidb/pulls?q=is%3Apr+label%3Asig%2Fsql-infra+reviewed-by%3AJmPotato+ and https://github.com/pingcap/parser/pulls?q=is%3Apr+reviewed-by%3AJmPotato+.

**Comment by JmPotato** [comment]
> I think the PR reviews are not enough as said in the sig-sql-infra roles-and-organization(20 reviews). I am OK to the promotion but I think we should at least meet this requirement.
> 
> Count: [https://github.com/pingcap/tidb/pulls?q=is%3Apr+label%3Asig%2Fsql-infra+reviewed-by%3AJmPotato+](https://github.com/pingcap/tidb/pulls?q=is%3Apr+label%3Asig%2Fsql-infra+reviewed-by%3AJmPotato+sort%3Aupdated-desc) and [https://github.com/pingcap/parser/pulls?q=is%3Apr+reviewed-by%3AJmPotato+](https://github.com/pingcap/parser/pulls?q=is%3Apr+reviewed-by%3AJmPotato+sort%3Aupdated-desc).

I think the rule is "Have at least 20 PRs (at least 10 PRs in tidb repo) merged.", so it should be 20 merged PRs, not reviewed?

Ref: https://github.com/pingcap/community/blob/master/special-interest-groups/sig-sql-infra/roles-and-organization-management.md#from-active-contributor-to-reviewer

**Comment by xhebox** [comment]
https://github.com/pingcap/tidb/pulls?q=is%3Apr+label%3Asig%2Fsql-infra+author%3AJmPotato+sort%3Aupdated-desc+
https://github.com/pingcap/parser/pulls?q=is%3Apr+author%3AJmPotato+sort%3Aupdated-desc+
8+2 infra PRs?

**Comment by JmPotato** [comment]
> [pingcap/tidb/pulls (label:sig/sql-infra author:JmPotato sort:updated-desc)](https://github.com/pingcap/tidb/pulls?q=is%3Apr+label%3Asig%2Fsql-infra+author%3AJmPotato+sort%3Aupdated-desc+)
> [pingcap/parser/pulls (author:JmPotato sort:updated-desc)](https://github.com/pingcap/parser/pulls?q=is%3Apr+author%3AJmPotato+sort%3Aupdated-desc+)
> 8+2 infra PRs?

😢 I didn't notice that the merged PR should have `sig/sql-infra` label. It seems that I still have a long way to go...

**Comment by tisonkun** [comment]
closed as unqualified. @JmPotato you can always reopen this issue or create a new one once you want to request again when qualified.
