### ISSUE TITLE
REQUEST: New membership for Howie59

### ISSUE THREAD

**Issue by Howie59** [pingcap/community#460]
### GitHub Username
@howie59

### SIG you are requesting membership in
- sig-name: sig-infra
- role: active contributor

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @djshow832 
- @tiancaiamao 

### List of contributions to the SIG’s project
- PRs [10+prs merged](https://github.com/pingcap/tidb/pulls?q=is%3Aopen+is%3Apr+author%3Ahowie59+infra%3A+)
- SIG projects I am involved with: sig-sql-infra

**Comment by djshow832** [comment]
LGTM

**Comment by tiancaiamao** [comment]
LGTM
