### ISSUE TITLE
REQUEST: New membership for @guo-shaoge

### ISSUE THREAD

**Issue by guo-shaoge** [pingcap/community#462]
### GitHub Username
@guo-shaoge

### SIG you are requesting membership in
- sig-name: sig-exec
- role: reviewer

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @XuHuaiyu 
- @lzmhhh123 

### List of contributions to the SIG’s project
- PRs [reviewed](https://github.com/pingcap/tidb/pulls?q=is%3Apr+reviewed-by%3Aguo-shaoge+label%3Asig%2Fexecution+is%3Aclosed+) / [authored](https://github.com/pingcap/tidb/pulls?q=is%3Apr+author%3Aguo-shaoge+label%3Asig%2Fexecution+is%3Aclosed+)
- Issues responded to: [35 issues](https://github.com/pingcap/tidb/issues?q=is%3Aissue+commenter%3Aguo-shaoge)
- SIG projects I am involved with: sig-exec

**Comment by lzmhhh123** [comment]
+1

**Comment by XuHuaiyu** [comment]
+1

**Comment by Mini256** [comment]
> * PRs reviewed / authored
> * Issues responded to
> * SIG projects I am involved with

Please fill these fields.

**Comment by guo-shaoge** [comment]
> > * PRs reviewed / authored
> > * Issues responded to
> > * SIG projects I am involved with
> 
> Please fill these fields.

Done.
