### ISSUE TITLE
REQUEST: New membership for @ichn-hu

### ISSUE THREAD

**Issue by ichn-hu** [pingcap/community#463]
### GitHub Username

@ichn-hu 

### SIG you are requesting membership in
- sig-name: sig-execution
- role: committer

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @XuHuaiyu 
- @wshwsh12 

### List of contributions to the SIG’s project
- PRs [reviewed](https://github.com/pingcap/tidb/pulls?q=is%3Apr+reviewed-by%3Aichn-hu+label%3Asig%2Fexecution+is%3Aclosed) / [authored](https://github.com/pingcap/tidb/pulls?q=is%3Apr+author%3Aichn-hu+label%3Asig%2Fexecution+is%3Aclosed+)
- Issues responded to [137](https://github.com/pingcap/tidb/issues?q=is%3Aissue+commenter%3Aichn-hu)
- SIG projects I am involved with: sig-exec

**Comment by wshwsh12** [comment]
+1

**Comment by XuHuaiyu** [comment]
+1

**Comment by Mini256** [comment]
> * PRs reviewed / authored
> * Issues responded to
> * SIG projects I am involved with

Please fill these fields.

**Comment by Mini256** [comment]
> > * PRs reviewed / authored
> > * Issues responded to
> > * SIG projects I am involved with
> 
> Please fill these fields.

ping~ @ichn-hu

**Comment by ichn-hu** [comment]
@Mini256 done!
