### ISSUE TITLE
REQUEST: New membership for @dveeden

### ISSUE THREAD

**Issue by morgo** [pingcap/community#465]
### GitHub Username

@dveeden 

### SIG you are requesting membership in
- sig-name: e.g. sig-docs
- role: reviewer

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application (N/A - not a self-request)

### Sponsors
- @morgo
- @TomShawn 

### List of contributions to the SIG’s project
- PRs reviewed / authored: https://github.com/pingcap/docs/pulls?q=is%3Apr+author%3Adveeden+is%3Aclosed
- Issues responded to: https://github.com/pingcap/docs/issues?q=is%3Aissue+%40dveeden+is%3Aopen+
- SIG projects contributor am involved with: docs, tidb, tiup.

**Comment by TomShawn** [comment]
LGTM
