### ISSUE TITLE
REQUEST: New membership for @zhuo-zhi

### ISSUE THREAD

**Issue by zhuo-zhi** [pingcap/community#469]
### GitHub Username
@zhuo-zhi

### SIG you are requesting membership in
- sig-name: sig-planner
- role: reviewer

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @qw4990 
- @winoros 

### List of contributions to the SIG’s project
- PRs reviewed / authored: no reviewed PRs, 11 merged PRs
- Issues responded to: 3 effective proposed issues
- SIG projects I am involved with: partition table in Sprint 3

**Comment by Mini256** [comment]
> PRs reviewed / authored
> Issues responded to
> SIG projects I am involved with

@zhuo-zhi Please fill in this information, after the sponsors pass the nominations by comment `+1`, I will help you submit the PR to update the SIG membership.

**Comment by qw4990** [comment]
+1

**Comment by winoros** [comment]
+1

**Comment by qw4990** [comment]
PTAL @Mini256
