### ISSUE TITLE
REQUEST: New membership for Leavrth

### ISSUE THREAD

**Issue by Leavrth** [pingcap/community#480]
### GitHub Username
@Leavrth 

### SIG you are requesting membership in
- sig-name: sig-migration
- role: committer

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @3pointer 
- @kennytm 

### List of contributions to the SIG’s project
- PRs [reviewed](https://github.com/pingcap/br/pulls?q=is%3Apr+reviewed-by%3ALeavrth+is%3Aclosed+) / [authored](https://github.com/pingcap/br/pulls?q=is%3Apr+author%3ALeavrth+is%3Aclosed+)
- Issues responded to [2 issues](https://github.com/pingcap/br/issues?q=is%3Aissue+commenter%3ALeavrth)
- SIG projects I am involved with: sig-migration

**Comment by Mini256** [comment]
Waiting for approval from two sponsors via comment `+1`.

**Comment by 3pointer** [comment]
+1

**Comment by kennytm** [comment]
+1
