### ISSUE TITLE
REQUEST: New membership for bufferflies

### ISSUE THREAD

**Issue by bufferflies** [pingcap/community#486]
### GitHub Username
@bufferflies 

### SIG you are requesting membership in
- sig-name: sig-scheduling
- role: Active Contributor

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @HunDunDM 
- @nolouch 

### List of contributions to the SIG’s project
- PRs  authored : https://github.com/tikv/pd/pulls?q=is%3Amerged+is%3Apr+author%3Abufferflies+sort%3Aupdated-desc+
- Issues responded to:https://github.com/tikv/pd/issues?q=is%3Aopen+mentions%3Abufferflies+sort%3Aupdated-desc+
- SIG projects I am involved with:

**Comment by Mini256** [comment]
```
PRs authored
Issues responded to
SIG projects I am involved with
```
Please fill in the above fields.

**Comment by nolouch** [comment]
lgtm

**Comment by Mini256** [comment]
It needs to be approved by two sponsors. It's better to use the `+1` comment uniformly to indicate that the nomination is approved.

**Comment by rleungx** [comment]
+1

**Comment by Mini256** [comment]
I found that the request you submit to join TiKV's SIG, but in fact, TiKV no longer uses the concept of SIG.

@tisonkun, Can you have a look?

**Comment by tisonkun** [comment]
Weird...TiKV community has nothing to do with pingcap/community. I will reach @nolouch & @rleungx and guide them follow TiKV process.

**Comment by tisonkun** [comment]
ref https://github.com/tikv/community/pull/136
