### ISSUE TITLE
REQUEST: New membership for gozssky

### ISSUE THREAD

**Issue by gozssky** [pingcap/community#488]
### GitHub Username
@gozssky 

### SIG you are requesting membership in
- sig-name: sig-migrate
- role: reviewer

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @kennytm 
- @3pointer 

### List of contributions to the SIG’s project
- PRs [reviewed](https://github.com/pingcap/br/pulls?q=is%3Apr++reviewed-by%3Agozssky+) / [authored](https://github.com/pingcap/br/pulls/gozssky)
- [Issues ](https://github.com/pingcap/br/issues?q=is%3Aissue+commenter%3Agozssky)responded to
- SIG projects I am involved with: sig-migrate

**Comment by kennytm** [comment]
the number of PRs reviewed (13 — that's including cherry-picks which ought not to be counted but anyway) does not quite meet the [requirement](https://github.com/pingcap/community/blob/master/special-interest-groups/sig-migrate/roles-and-organization-management.md#promotion) yet (20). perhaps requesting for "Reviewer" first is more appropriate.

**Comment by gozssky** [comment]
> the number of PRs reviewed (13 — that's including cherry-picks which ought not to be counted but anyway) does not quite meet the [requirement](https://github.com/pingcap/community/blob/master/special-interest-groups/sig-migrate/roles-and-organization-management.md#promotion) yet (20). perhaps requesting for "Reviewer" first is more appropriate.

updated

**Comment by kennytm** [comment]
+1

**Comment by 3pointer** [comment]
+1

**Comment by gozssky** [comment]
@Mini256 PTAL
