### ISSUE TITLE
REQUEST: New membership for KanShiori

### ISSUE THREAD

**Issue by KanShiori** [pingcap/community#496]
### GitHub Username
@KanShiori 

### SIG you are requesting membership in
- sig-name: sig-k8s
- role: reviewer

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @csuzhangxc 
- @DanielZhangQD 

### List of contributions to the SIG’s project
- PRs authored 20 https://github.com/pingcap/tidb-operator/pulls?q=is%3Apr+author%3AKanshiori+
- Fix issue 7 https://github.com/pingcap/tidb-operator/issues?q=is%3Aissue+assignee%3AKanshiori+is%3Aclosed+
- Issues responded to
- SIG projects I am involved with

**Comment by csuzhangxc** [comment]
+1

**Comment by DanielZhangQD** [comment]
+1

**Comment by Mini256** [comment]
Please remove the `e.g.` in the pr body, it means for example.

You also need to review the [roles-and-organization-management.md ](https://github.com/pingcap/community/blob/master/special-interest-groups/sig-k8s/roles-and-organization-management.md), there are some SIG specific requirements you need to satisfy.

> Have reviewed at least 20 PRs in #sig-k8s projects

**Comment by KanShiori** [comment]
> Please remove the `e.g.` in the pr body, it means for example.
> 
> You also need to review the [roles-and-organization-management.md ](https://github.com/pingcap/community/blob/master/special-interest-groups/sig-k8s/roles-and-organization-management.md), there are some SIG specific requirements you need to satisfy.
> 
> > Have reviewed at least 20 PRs in #sig-k8s projects


I changed role to reviewer, please check again.
