### ISSUE TITLE
Auto-tune RocksDB

### ISSUE THREAD

**Issue by winkyao** [pingcap/community#50]
(This is an example issue of TiDB Performance Challenge Program. Please don't open/assign this issue)

* Description: TiKV heavily depends on RocksDB, but RocksDB has many configurations and it is hard to choose proper values in production. The goal for this section is to auto-tune RocksDB in real-time for different workloads.
* Recommended Skills: Rust, RocksDB
* Mentor(s): Yi Wu (@yiwu-arbug)
* Issue: https://github.com/tikv/tikv/issues/4052
* Peer Bonus: 1000

**Comment by siddontang** [comment]
I think @pentium3 has been doing this.
