### ISSUE TITLE
REQUEST: New membership for Ehco1996

### ISSUE THREAD

**Issue by Ehco1996** [pingcap/community#502]
### GitHub Username
@Ehco1996 

### SIG you are requesting membership in
- sig-name: sig-migrate
- role: committer

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @lichunzhu 
- @lance6716 

### List of contributions to the SIG’s project
- PRs reviewed / authored  
    * [DM 26](https://github.com/pingcap/dm/pulls?q=is%3Apr+is%3Amerged+author%3AEhco1996)
    * [tidb-tools 2](https://github.com/pingcap/tidb-tools/pulls?q=is%3Apr+is%3Amerged+author%3AEhco1996+)
    * [dumpling 2](https://github.com/pingcap/dumpling/pulls?q=is%3Apr+author%3AEhco1996+)
    * [reviewed 54](https://github.com/pingcap/dm/pulls?q=type%3Apr+reviewed-by%3AEhco1996)
- Issues responded to
- SIG projects I am involved with

**Comment by Mini256** [comment]
Could you please list PRs that you reviewed through this [search syntax](https://docs.github.com/en/github/searching-for-information-on-github/searching-on-github/searching-issues-and-pull-requests#search-by-pull-request-review-status-and-reviewer)

**Comment by Ehco1996** [comment]
> Could you please list PRs that you reviewed through this [search syntax](https://docs.github.com/en/github/searching-for-information-on-github/searching-on-github/searching-issues-and-pull-requests#search-by-pull-request-review-status-and-reviewer)

thanks for review updated [reviewed 54](https://github.com/pingcap/dm/pulls?q=type%3Apr+reviewed-by%3AEhco1996)

**Comment by Mini256** [comment]
> thanks for review updated [reviewed 54](https://github.com/pingcap/dm/pulls?q=type%3Apr+reviewed-by%3AEhco1996)

ok, I will approve the promotion PR after the sponsors approve the promotion through commenting `+1` on this issue.

**Comment by lance6716** [comment]
+1

**Comment by kennytm** [comment]
+1

**Comment by lichunzhu** [comment]
+1
