### ISSUE TITLE
REQUEST: New membership for hi-rustin

### ISSUE THREAD

**Issue by hi-rustin** [pingcap/community#506]
### GitHub Username
e.g. @hi-rustin 

### SIG you are requesting membership in
- sig-name: sig-migrate
- role: reviewer

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @overvenus 
- @amyangfei 

### List of contributions to the SIG’s project
- PRs reviewed / authored
  -  [TiCDC 30 PRs (20 merged) ](https://github.com/pingcap/ticdc/pulls/hi-rustin)
  -  [TiKV 1 simple PR for TiCDC ](https://github.com/tikv/tikv/pull/10482)
  -  [CI 2 PRs](https://github.com/PingCAP-QE/ci/pulls?q=is%3Apr+author%3Ahi-rustin+is%3Aclosed)
- Issues responded to
  - [TiCDC 18 issues](https://github.com/tikv/tikv/issues?q=is%3Aissue+is%3Aopen+commenter%3Ahi-rustin)
  Also, I fixed a moderately difficult issue. 
- SIG projects I am involved with
  - TiCDC
  - Tikv

**Comment by amyangfei** [comment]
Approved 👏

**Comment by overvenus** [comment]
Awesome! 👍
