### ISSUE TITLE
REQUEST: New membership for en-jin19

### ISSUE THREAD

**Issue by en-jin19** [pingcap/community#507]
### GitHub Username
@en-jin19

### SIG you are requesting membership in
- sig-name: docs SIG
- role: Active Contributor

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @TomShawn 
- @qiancai 

### List of contributions to the SIG’s project
- PRs authored:
  - https://github.com/pingcap/docs/pulls?q=is%3Apr+author%3Aen-jin19+is%3Aclosed (8 in total)
  - https://github.com/pingcap/docs-cn/pulls?q=is%3Apr+author%3Aen-jin19+is%3Aclosed (4 in total)

**Comment by Mini256** [comment]
@TomShawn, @qiancai Could you mind taking a look, if you agree with this promotion, you can reply through the `+1` comment.

**Comment by TomShawn** [comment]
LGTM

**Comment by Mini256** [comment]
@qiancai ping~

**Comment by tisonkun** [comment]
We don't have active contributor ladder any longer. Please refer to [team governance](https://github.com/pingcap/community/blob/master/teams/README.md) page for details. I think @qiancai can guide you to participant docs team well.

Closed as invalid.
