### ISSUE TITLE
REQUEST: New membership for @lcwangchao

### ISSUE THREAD

**Issue by lcwangchao** [pingcap/community#511]
### GitHub Username
@lcwangchao 

### SIG you are requesting membership in
- sig-name: sig-sql-infra
- role: reviewer

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @djshow832 
- @tiancaiamao 

### List of contributions to the SIG’s project
- PRs reviewed / authored
  - [TiDB 26 PRs](https://github.com/pingcap/tidb/pulls?q=author%3Alcwangchao)
  - [Parser 1 PR](https://github.com/pingcap/parser/pulls?q=+is%3Apr+author%3Alcwangchao)
- Issues responded to
  - [TiDB 17 issues](https://github.com/pingcap/tidb/issues?q=+is%3Aissue+assignee%3Alcwangchao+)
- SIG projects I am involved with
  - sig-sql-infra

**Comment by djshow832** [comment]
LGTM

**Comment by tiancaiamao** [comment]
LGTM

**Comment by Mini256** [comment]
> PRs reviewed / authored
> Issues responded to
> SIG projects I am involved with

Please fill in these fields. 

For example: https://github.com/pingcap/community/issues/506

**Comment by lcwangchao** [comment]
> > PRs reviewed / authored
> > Issues responded to
> > SIG projects I am involved with
> 
> Please fill in these fields.
> 
> For example: #506

Done
