### ISSUE TITLE
REQUEST: New membership for @xuyifangreeneyes

### ISSUE THREAD

**Issue by xuyifangreeneyes** [pingcap/community#517]
### GitHub Username
@xuyifangreeneyes 

### SIG you are requesting membership in
- sig-name: sig-planner
- role: reviewer

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @winoros 
- @qw4990 

### List of contributions to the SIG’s project
- PRs [reviewed](https://github.com/pingcap/tidb/pulls?q=is%3Apr+reviewed-by%3Axuyifangreeneyes+label%3Asig%2Fplanner+is%3Aclosed+) / [authored](https://github.com/pingcap/tidb/pulls?q=is%3Apr+author%3Axuyifangreeneyes+label%3Asig%2Fplanner+is%3Aclosed+)
- Issues responded to [issues](https://github.com/pingcap/tidb/issues?q=is%3Aissue+commenter%3Axuyifangreeneyes)
- SIG projects I am involved with: index selection, dynamic partition table stats, tiflash fall back to tikv.

**Comment by winoros** [comment]
+1

**Comment by qw4990** [comment]
+1

**Comment by xuyifangreeneyes** [comment]
@Mini256 PTAL
