### ISSUE TITLE
REQUEST: New membership for asddongmen

### ISSUE THREAD

**Issue by asddongmen** [pingcap/community#528]
### GitHub Username
asddongmen

### SIG you are requesting membership in
- sig-name: sig-migrate
- role: reviewer

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @amyangfei 
- @leoppro 

### List of contributions to the SIG’s project
- PRs [reviewed](https://github.com/pingcap/ticdc/pulls?q=is%3Apr+reviewed-by%3A%40me+is%3Aclosed) 39 items / [authored](https://github.com/pingcap/ticdc/pulls?q=is%3Apr+is%3Aclosed+author%3Aasddongmen) 23 items
- Issues responded to ：[TiCDC](https://github.com/pingcap/ticdc/issues?q=is%3Aissue+assignee%3Aasddongmen+is%3Aclosed)  22 items 
- SIG projects I am involved with：sig-migration

**Comment by amyangfei** [comment]
Approved. 👏👏

**Comment by leoppro** [comment]
Approved.

**Comment by leoppro** [comment]
@Mini256 PTAL
