### ISSUE TITLE
Fix wrong help-wanted issues link

### ISSUE THREAD

**Issue by karuppiah7890** [pingcap/community#530]
In this doc - https://github.com/pingcap/community/blob/master/contributors/README.md#your-first-contribution , the link to help-wanted issues seems to be wrong

Wrong link - https://github.com/pingcap/tidb/issues?q=is%3Aissue+is%3Aopen+label%3Astatus%2Fhelp-wanted

Right link - https://github.com/pingcap/tidb/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22

**Comment by tisonkun** [comment]
Thanks for your reporting this. I think you can just open a PR to fix it.

By the way, we're trying to factor out contributing guide into our [TiDB Dev Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb) and you can find a section ["Looking for what to contribute"](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/contribute-code.html#looking-for-what-to-contribute). I think the "contributors" folder in this repo will be removed as #525 going on.
