### ISSUE TITLE
The link of roadmap is not accessible.

### ISSUE THREAD

**Issue by Defined2014** [pingcap/community#549]
As described in the title, PTAL.

https://github.com/pingcap/community#tidb-roadmap

**Comment by tisonkun** [comment]
Yes. We don't have a roadmap any longer.

cc @TomShawn @winkyao

**Comment by TomShawn** [comment]
> Yes. We don't have a roadmap any longer.
> 
> cc @TomShawn @winkyao

According to the suggestion of the release team, this roadmap document has been removed from PingCAP docs. Please also remove the link in https://github.com/pingcap/community#tidb-roadmap. Thanks!
