### ISSUE TITLE
REQUEST: New membership for KanShiori

### ISSUE THREAD

**Issue by KanShiori** [pingcap/community#597]
### GitHub Username
@KanShiori 

### SIG you are requesting membership in
- sig-name: sig-k8s
- role: commiter

### Requirements
- [x] I have reviewed the SIG promotion process guidelines(https://docs.google.com/document/d/1OvlpU00W_LpTL09zB3gvDyQzHULz27kmNKH2O0seWCI/edit?usp=sharing)
- [x] I am actively contributing to this SIG
- [x] I have two sponsors that meet the SIG roles-and-organization-management requirements
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @csuzhangxc 
- @DanielZhangQD 

### List of contributions to the SIG’s project
- PRs [reviewed](https://github.com/pingcap/tidb-operator/pulls?q=is%3Apr+reviewed-by%3AKanShiori+is%3Aclosed+) 32/ [authored](https://github.com/pingcap/tidb-operator/pulls?q=is%3Apr+is%3Aclosed+author%3AKanshiori)  65
- Issues responded to 
- SIG projects I am involved with sig-k8s

**Comment by csuzhangxc** [comment]
+1

**Comment by DanielZhangQD** [comment]
+1

**Comment by KanShiori** [comment]
@Mini256 PTAL

**Comment by Mini256** [comment]
@KanShiori Congrats for you! But our nomination process has changed, you can refer to this [doc](https://github.com/pingcap/community/tree/master/teams) and read it carefully, you can delegate the maintainers to help you submit nominated voting.

cc: @pingcap/kubernetes-maintainers

For example: https://github.com/pingcap/community/pull/592
