### ISSUE TITLE
Force PR issue association

### ISSUE THREAD

**Issue by zhangyangyu** [pingcap/community#604]
- [x] Propose for PR issue association https://github.com/pingcap/community/pull/606
- [x] Modify PR template https://github.com/pingcap/tidb/issues/30814 https://github.com/pingcap/tidb-tools/issues/567 https://github.com/pingcap/tidb-binlog/issues/1098 https://github.com/pingcap/tiflow/issues/3967 https://github.com/pingcap/ng-monitoring/issues/64
- [x] Apply PR body checker https://github.com/ti-community-infra/configs/pull/472 
- [x] Apply new tide https://github.com/ti-community-infra/test-infra
- [x] Update TiDB dev guide for  PR issue association checker https://github.com/pingcap/tidb-dev-guide/pull/185

**Comment by Mini256** [comment]
We also need to modify the PR template of other repositories (pingcap/tidb-tools, pingcap/tidb-binlog, pingcap/tiflow, pingcap/ng-monitoring).

In addition, we also need to deploy @ti-chi-bot on the pingcap/ng-monitoring repo.

**Comment by zhangyangyu** [comment]
> We also need to modify the PR template of other repositories (pingcap/tidb-tools, pingcap/tidb-binlog, pingcap/tiflow, pingcap/ng-monitoring).
> 
> In addition, we also need to deploy @ti-chi-bot on the pingcap/ng-monitoring repo.
Okay, I'll take the template thing.
