### ISSUE TITLE
@morgo is still one of TiDB committer, but removed from the org?

### ISSUE THREAD

**Issue by tisonkun** [pingcap/community#670]
@morgo is this your request? Would you like to stay in TiDB committer group?

**Comment by morgo** [comment]
Yes please - I will still be working on tidb in my new position. Thanks!

**Comment by tisonkun** [comment]
@zhangyangyu could you help on this issue? Perhaps it's a mistake to remove active committers.

**Comment by zhangyangyu** [comment]
It's definitely not right. You should not be removed from the tidb-committers team. I've resent an invitation to you @morgo . Sorry for it.

**Comment by tisonkun** [comment]
Closed as invited and joined. However, IIRC @morgo is previously a member of @pingcap/tidb-configuration-reviewer. I'm unsure whether this role should be retained. cc @bb7133
