### ISSUE TITLE
Need code style guides for golang and rust

### ISSUE THREAD

**Issue by shenli** [pingcap/community#75]
We need something like https://github.com/uber-go/guide/blob/master/style.md
So the community could follow the guide to produce unique style and high-quality code.

**Comment by gregwebs** [comment]
I suggest focusing first on having consistent automated linting tooling everywhere (we are using the revive linter in some go projects now, but not necessarily consistently). A guide is very good for those consistently involved in the project but new open source contributor shouldn't have to read through a guide, and code reviewers should spend more time finding bugs rather than correcting things that machines can.

**Comment by Hoverbear** [comment]
@nrc and @breeswish are working on this for TiKV right now. :)

**Comment by shenli** [comment]
@gregwebs Yes, unified linting tool is necessary. But as a large project, TiDB needs a code guide. For example, contributors should follow the same way to format error messages. 
We have plan to gain more active contributors. The guides would be helpful for them.

**Comment by gregwebs** [comment]
I agree that a guide is also good. I am just trying to share my opinion that as a new contributor an automated linter that runs on pull requests that I can also easily run locally is more valuable to me.

**Comment by nrc** [comment]
The guide is being developed at https://github.com/nrc/pingcap-style-guide The first draft is almost complete and I will move into the TiKV or PingCAP org soon

**Comment by Hoverbear** [comment]
Posted on https://pingcap.github.io/style-guide/rust/ now

**Comment by zz-jason** [comment]
Referencing [pingcap/style-guide](https://github.com/pingcap/style-guide) in the [Coding Style](https://github.com/pingcap/community/pull/79/files#diff-d617de87ae2c94db07a7803ede328e4aR101-R104) part of `how to contribute`.

**Comment by spjich** [comment]
****

**Comment by tisonkun** [comment]
closed as partially done.

* Go part published at https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/code-style-and-quality-guide.html
* Rust part published at https://pingcap.github.io/style-guide/rust/
