### ISSUE TITLE
Incubating Program: TiDB with WebAssembly

### ISSUE THREAD

**Issue by lucklove** [pingcap/community#83]
## Incubating Program

TiDB with WebAssembly

#### Summary

TiDB has a community, as does WebAssembly. As WebAssembly technology matures, more and more applications will be running in browsers, and users no longer have to endure cumbersome downloads and installation processes, which greatly reduces the cost of promoting these applications. Obviously users who are using TiDB for the first time are faced with these problems, so we can use WebAssembly technology to reduce the barriers to user engagement with TiDB, and we can also expand the TiDB audience with the help of the WebAssembly community.

#### Motivation

This proposal is expected to achieve these goals:
- TiDB can work properly in browsers such as chrome/firefox on PC(done)
- tour.tidb.io and play.tidb.io can be used as play ground(done)
- support community project such as [tidb-wasm-markdown](https://github.com/imiskolee/tidb-wasm-markdown)
- TiDB can work properly in browsers on phones
- TiDB can run in wasmer and can be deployed to [WebAssembly Shell](https://webassembly.sh/)

This proposal mainly solves the following problems: 
- compiling TiDB to WebAssembly will encounter the the problem that TiDB or third-party libraries may not be compatible with Wasm, so compilation will fail, the code need to be modified accordingly.
- Before running TiDB's WebAssembly result in browser, we should fix some issues:
  - There are some compatibility issues in Golang's current version
  - TiDB can't listen on a specific port or access file in browser since the security strategy
- Before running TiDB's WebAssembly result in phone, we should fix:
  - The webkit has a [limit](https://trac.webkit.org/browser/webkit/branches/safari-604.1-branch/Source/JavaScriptCore/jit/ExecutableAllocator.cpp#L90) on the executable memory, typically it's 64M, however, the result of TiDB is 76M
  - The browser in phone has different events than which in PC, so the SQL terminal must be compatible with both
- Before running with wasmer, the TiDB should be compiled to WASI, however:
  - Golang doesn't support WASI very well, we must use a [fork of Golang](https://github.com/neelance/go/tree/wasi)
  - The TiDB result is so large, we should make it smaller

#### Estimated Time

30 days

### Your RFC/Proposal?

https://github.com/pingcap/tidb/pull/13570

**Comment by winkyao** [comment]
LGTM

**Comment by qiuyesuifeng** [comment]
LGTM

**Comment by zz-jason** [comment]
LGTM

**Comment by hi-rustin** [comment]
/close

The issue has not been replied for a long time, so I will close the issue.

If the issue needs to be discussed, please reply to request reopen, and I will reopen the issue for you.
