### ISSUE TITLE
Incubating Program: KeyVisualizer: The visualized hotspot profiler

### ISSUE THREAD

**Issue by andylokandy** [pingcap/community#88]
## Incubating Program

KeyVisualizer: The visualized hotspot profiler

#### Summary

Add an enabled-by-default `KeyVisualizer` component to `PD`, providing a visual webpage to show key heatmap of the `TiKV` cluster, which is useful for troubleshooting and reasoning inefficient application usage patterns. `KeyVisualizer` is accessible in-browser via the URL from `PD`.

#### Motivation

At present, if someone wants to troubleshoot a performance issue in `TiKV`, he will usually make use of some existing diagnostic tools, such as `pd-ctl`, `Prometheus` and `Grafana`, which are hard to learn, intuitive, not efficient, unable to recognize the pattern of application and hard to make correct judgment basing on them.

Google `BigTable` has similar problems. So they provided a heatmap profiler called [`BigTable KeyVisualizer`](https://cloud.google.com/bigtable/docs/keyvis-overview) ([Video](https://youtu.be/aKJlghIygQw)), which is recommended that the user first use to troubleshoot performance problems. After investigation, we realized that it has
good features that also suits `TiKV`, thus we added some of those features to our design.

#### Estimated Time

30 days

### Your RFC/Proposal?
https://github.com/tikv/rfcs/pull/36

**Comment by winkyao** [comment]
LGTM

**Comment by siddontang** [comment]
LGTM

**Comment by qiuyesuifeng** [comment]
LGTM

**Comment by tisonkun** [comment]
@HunDunDM is this feature already done? If so, please comment the related issue or PR.

**Comment by andylokandy** [comment]
> @HunDunDM is this feature already done? If so, please comment the related issue or PR.

The related repo is deleted, so I think you are free to close this.

**Comment by tisonkun** [comment]
@andylokandy thanks. Closing...
